  # docker-compose.yaml
  version: '3.8'
  services:
    jenkins_maven:
      image: chrisslima/s107-jenkins-maven
      container_name: jenkins
      privileged: true
      user: root
      ports:
       - 8080:8080
       - 50000:50000
      volumes:
        - ./jenkins_compose/jenkins_configuration:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock

    mongodb:
      image: mongo
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      volumes:
        - /Users/user/Documents/mongodb:/data/db
    
    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: root
        ME_CONFIG_MONGODB_SERVER: mongodb